name: conda-env

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: s-weigand/setup-conda@v1.0.2
    - name: Conda info
      run: | 
        conda --version
        which python
    - name: Display current environments
      run: conda info --envs
    - name: Update environment
      run: |
        conda env update -n base -f ./pyaerocom_env.yml
    - name: Install pytest
      run: | 
        conda install pytest
        conda info --envs
        conda list pytest
        which python
    - name: Install pyaerocom
      run: python ./setup.py install
    - name: Run pytest
      run: pytest
